### ISSUE TITLE
Docker-out-of-Docker (DooD) Solution

### ISSUE THREAD

**Issue by sebastientourbier** [brainhack-ch/superres-mri#5]
**Brainhack Global Geneva 2019 Challenge**

Build and run a Docker image executes a nipype workflow that should run an other Docker image that contains the C++ NLMdenoising program of the MIALSRTK library.

**Road Map:**

- [x] Creation of first sinapp workflow with BIDS App parser (python / not containerized yet)
- [x] Creation of Dockerfile
- [x] Build, test, and make it work

**Comment by sebastientourbier** [comment]
**Summary of challenges and solutions**

* Access the docker engine of the OS host from within the first container

  **Solution:** Adopting the Docker-out-of-Docker framework maps `/var/run/docker.sock` into the first container, enabling the first container to access Docker running on the OS host. 

  ![0D679D22-0C43-436E-8BAC-D2A7FCCCF45A](https://user-images.githubusercontent.com/22279770/68497353-a52e3a00-0254-11ea-9741-6506b9f37685.jpeg)

  It seems we also have to map  `/usr/bin/docker`.

* User/group permissions to access the docker.sock mapped within the first container 
  
  **Solution:** Use of `docker run -u $(id -u):$(id -g) --group-add 0` to add the current user/group to docker group that seems to be 0.

* Access the BIDS dataset from the second container
  
  **Solution:** Give a name to the first container at execution with `docker run --name sinapp_nlmdenoise -v <local/path/to/bids>:/fetaldata` that also mounts your local bids directory as the `/fetaldata` volume of this container and then at the execution of the second container use `docker run --volumes-from sinapp_nlmdenoise` to be able to access to the volume `/fetaldata` mount in the first (SINAPP) container.

**Comment by sebastientourbier** [comment]
See Commit 6ffe6b855e914edbb87e43ff10a7f5718ce41d1a for changes that made the first SINAPP working

**Comment by sebastientourbier** [comment]
**Summary of challenges and solutions**

* User/group permissions to access the docker.sock mapped within the first container 
  
  **Solution:** Use of `docker run -u $(id -u):$(id -g) --group-add 0` to add the current user/group to docker group that seems to be 0.

* Access the BIDS dataset from the second container
  
  **Solution:** Give a name to the first container at execution with `docker run --name sinapp_nlmdenoise -v <local/path/to/bids>:/fetaldata` that also mounts your local bids directory as the `/fetaldata` volume of this container and then at the execution of the second container use `docker run --volumes-from sinapp_nlmdenoise` to be able to access to the volume `/fetaldata` mount in the first (SINAPP) container.
